  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=quiz
        - POSTGRES_USER=gsbaker
        - POSTGRES_PASSWORD=d=sC^9yszej<ND!
    web:
      build: .
      command: python mysite/manage.py runserver 0.0.0.0:8000
      volumes:
        - ./:/usr/src/app
      ports:
        - "8000:8000"
      depends_on:
        - db
